version: '3.7'
services:
  mysql:
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nette-task
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - nette-blog
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
  php:
    platform: linux/x86_64
    build: ./.docker/php
    ports: ['9001:9000']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www']
    networks:
      - nette-blog

  nginx:
    build: ./.docker/nginx
    ports: ['80:80']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www']
    networks:
      - nette-blog

networks:
  nette-blog:
